# Use Python 3.11 slim image as base
FROM python:3.11-slim

# Set working directory in container
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    coreutils \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create directories for storing assets
RUN mkdir -p logo_store map_store

# Expose port
EXPOSE 8000

# Command to run the application with auto-reload
#CMD ["uvicorn", "src.__init__:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
CMD ["tail", "-f", "/dev/null"]