# Use Python 3.12 slim image as base
FROM python:3.12-slim

# Set working directory in container
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    coreutils \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Copy pyproject.toml file
COPY pyproject.toml .
COPY README.md .
# Install dependencies based on build argument
ARG INSTALL_DEV=false
RUN  if [ "${INSTALL_DEV}" = "true" ]; then pip install --no-cache-dir .[test,dev]; else pip install --no-cache-dir . ; fi


# Create directories for storing assets
RUN mkdir -p logo_store map_store

# Expose port
EXPOSE 8000
WORKDIR /app/src
# Command to run the application with auto-reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# CMD ["tail", "-f", "/dev/null"]