from availability.service import AvailabilityService
from services.audit import audit_service
from services.status import status_transition_service
availability_service = AvailabilityService(audit_service, status_transition_service)