"""new_models

Revision ID: ed84add7b20d
Revises: 72714e929344
Create Date: 2025-05-19 23:41:29.498526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM
import sqlmodel

# Import the enum classes directly from the models
from competitions.base_schemas import GameMode, LeagueFormat, MapCategory, MapSelectionMethod, TournamentState
from competitions.models.scheduling import AvailabilityStatus, AvailabilityType
from competitions.map_pool.models import MapPoolSelectionType, MapPoolStatus
from competitions.models.lobby import VetoActionType
from matches.evidence.models import EvidenceStatus
from matches.models import DisputeStatus
from moderation.models import ModerationActionType
from maps.models import Map
# revision identifiers, used by Alembic.
revision: str = 'ed84add7b20d'
down_revision: Union[str, None] = '72714e929344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create PostgreSQL ENUM types first, checking if they exist
    for enum_name, values in [
        ("gamemode", "'competitive_5v5', 'wingman_2v2', 'retake', 'deathmatch'"),
        ("mapcategory", "'competitive', 'wingman', 'hostage', 'custom'"),
        ("leagueformat", "'home_away', 'single_round_robin', 'double_round_robin', 'swiss'"),
        ("mapselectionmethod", "'admin_assigned', 'team_pick', 'map_veto', 'random'"),
        ("mapselectiontype", "'admin_defined', 'team_voting', 'player_voting'"),
        ("mapstatus", "'voting', 'finalized', 'cancelled'"),
        ("vetoactiontype", "'ban', 'pick', 'side'"),
        ("evidencestatus", "'pending', 'confirmed', 'disputed', 'rejected'"),
        ("disputestatus", "'pending', 'under_review', 'resolved', 'rejected', 'escalated'"),
        ("moderationactiontype", "'warning', 'suspension', 'ban', 'mute'"),
        ("availabilitytype", "'available', 'maybe', 'unavailable'"),
        ("availabilitystatus", "'active', 'cancelled', 'expired'"),
    ]:
        # Check if the enum exists first
        op.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}') THEN
                    CREATE TYPE {enum_name} AS ENUM ({values});
                END IF;
            END$$;
        """)
    
    # Handle tournamentstate separately since it seems to exist already
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tournamentstate') THEN
                CREATE TYPE tournamentstate AS ENUM ('not_started', 'in_progress', 'completed', 'cancelled');
            ELSE
                -- Check if we need to modify the existing enum
                IF NOT EXISTS (
                    SELECT 1 
                    FROM pg_enum 
                    WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'tournamentstate')
                    AND enumlabel = 'not_started'
                ) THEN
                    -- If the enum doesn't have our values, drop and recreate it
                    DROP TYPE tournamentstate CASCADE;
                    CREATE TYPE tournamentstate AS ENUM ('not_started', 'in_progress', 'completed', 'cancelled');
                END IF;
            END IF;
        END$$;
    """)

    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('action_type', postgresql.ENUM('warning', 'suspension', 'ban', 'mute', name='moderationactiontype', create_type=False), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('availability_type', postgresql.ENUM('available', 'maybe', 'unavailable', name='availabilitytype', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'cancelled', 'expired', name='availabilitystatus', create_type=False), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_pattern', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('available_players', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('maybe_players', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('unavailable_players', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('available_substitutes', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('has_minimum_players', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_map_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('selection_type', postgresql.ENUM('admin_defined', 'team_voting', 'player_voting', name='mapselectiontype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('voting', 'finalized', 'cancelled', name='mapstatus', create_type=False), nullable=False),
    sa.Column('voting_start', sa.DateTime(), nullable=True),
    sa.Column('voting_end', sa.DateTime(), nullable=True),
    sa.Column('maps_to_select', sa.Integer(), nullable=True),
    sa.Column('votes_per_team', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_pool_maps',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['tournament_map_pools.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'map_id')
    )
    op.create_table('map_pool_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('map_id', sa.UUID(), nullable=True),
    sa.Column('voted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['tournament_map_pools.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_veto_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_team_id', sa.UUID(), nullable=True),
    sa.Column('current_action', postgresql.ENUM('ban', 'pick', 'side', name='vetoactiontype', create_type=False), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('demo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stats_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'disputed', 'rejected', name='evidencestatus', create_type=False), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=True),
    sa.Column('conflict_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affected_players', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=True),
    sa.Column('suggested_time', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('available_players_team1', sa.Integer(), nullable=False),
    sa.Column('available_players_team2', sa.Integer(), nullable=False),
    sa.Column('conflicts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['players.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['match_evidence.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_veto_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('action_type', postgresql.ENUM('ban', 'pick', 'side', name='vetoactiontype', create_type=False), nullable=True),
    sa.Column('map_id', sa.UUID(), nullable=True),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['map_veto_sessions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('disputed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'under_review', 'resolved', 'rejected', 'escalated', name='disputestatus', create_type=False), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disputed_by'], ['players.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    op.add_column('maps', sa.Column('category', postgresql.ENUM('competitive', 'wingman', 'hostage', 'custom', name='mapcategory', create_type=False), nullable=True))
    op.add_column('maps', sa.Column('supported_modes', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('match_players', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('player_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('pug_map_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('pug_players', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('pug_players', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('pug_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('pugs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('results', sa.Column('voided', sa.Boolean(), nullable=False))
    op.add_column('results', sa.Column('voided_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rosters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rosters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('team_captains', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('tournaments', sa.Column('status', postgresql.ENUM('not_started', 'in_progress', 'completed', 'cancelled', name='tournamentstate', create_type=False), nullable=True))
    op.add_column('tournaments', sa.Column('game_mode', postgresql.ENUM('competitive_5v5', 'wingman_2v2', 'retake', 'deathmatch', name='gamemode', create_type=False), nullable=True))
    op.add_column('tournaments', sa.Column('league_format', postgresql.ENUM('home_away', 'single_round_robin', 'double_round_robin', 'swiss', name='leagueformat', create_type=False), nullable=True))
    op.add_column('tournaments', sa.Column('map_selection_method', postgresql.ENUM('admin_assigned', 'team_pick', 'map_veto', 'random', name='mapselectionmethod', create_type=False), nullable=True))
    op.add_column('tournaments', sa.Column('scheduling_config', sa.JSON(), nullable=True))
    
    # Check if 'state' column exists before dropping it
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_name = 'tournaments'
                AND column_name = 'state'
            ) THEN
                ALTER TABLE tournaments DROP COLUMN state;
            END IF;
        END$$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if state column exists before adding it (to avoid errors)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_name = 'tournaments'
                AND column_name = 'state'
            ) THEN
                ALTER TABLE tournaments ADD COLUMN state tournamentstate;
            END IF;
        END$$;
    """)
    
    # Drop columns (use safe drop in case they don't exist)
    for column in ['scheduling_config', 'map_selection_method', 'league_format', 'game_mode', 'status']:
        op.execute(f"""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'tournaments'
                    AND column_name = '{column}'
                ) THEN
                    ALTER TABLE tournaments DROP COLUMN {column};
                END IF;
            END$$;
        """)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_captains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rosters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rosters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('results', 'voided_reason')
    op.drop_column('results', 'voided')
    op.alter_column('pugs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pug_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pug_players', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('pug_players', 'created_at')
    op.alter_column('pug_map_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('match_players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('maps', 'supported_modes')
    op.drop_column('maps', 'category')
    op.alter_column('bans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('match_disputes')
    op.drop_table('map_veto_actions')
    op.drop_table('evidence_confirmations')
    op.drop_table('schedule_suggestions')
    op.drop_table('schedule_conflicts')
    op.drop_table('match_evidence')
    op.drop_table('map_veto_sessions')
    op.drop_table('map_pool_votes')
    op.drop_table('map_pool_maps')
    op.drop_table('tournament_map_pools')
    op.drop_table('team_availability')
    op.drop_table('player_availability')
    op.drop_table('moderation_actions')

    # Drop custom enum types
    op.execute("DROP TYPE IF EXISTS gamemode")
    op.execute("DROP TYPE IF EXISTS mapcategory")
    op.execute("DROP TYPE IF EXISTS leagueformat")
    op.execute("DROP TYPE IF EXISTS mapselectionmethod")
    op.execute("DROP TYPE IF EXISTS tournamentstate")
    op.execute("DROP TYPE IF EXISTS mapselectiontype")
    op.execute("DROP TYPE IF EXISTS mapstatus")
    op.execute("DROP TYPE IF EXISTS vetoactiontype")
    op.execute("DROP TYPE IF EXISTS evidencestatus")
    op.execute("DROP TYPE IF EXISTS disputestatus")
    op.execute("DROP TYPE IF EXISTS moderationactiontype")
    op.execute("DROP TYPE IF EXISTS availabilitytype")
    op.execute("DROP TYPE IF EXISTS availabilitystatus")
    # ### end Alembic commands ###
